export const ROOM_CONFIG = {
  MAX_PLAYERS: 8,
  MIN_PLAYERS: 2,
  ROUND_TIME: 60,
  SELECT_TIME: 10,
  MAX_ROUNDS: 3,
  POINTS_CORRECT_FIRST: 100,
  POINTS_CORRECT: 50,
  POINTS_DRAWER_PER_GUESS: 50
}
